name: 'data_profiling'
version: '0.1.2'
config-version: 2


profile: 'default'

vars:

  eligibility: "{% if project_name == 'data_profiling' %}{{ source('claims_input','eligibility') }}{% else %}{{ref('eligibility')}}{% endif %}"
  medical_claim: "{% if project_name == 'data_profiling' %}{{ source('claims_input','medical_claim') }}{% else %}{{ref('medical_claim')}}{% endif %}"
  pharmacy_claim: "{% if project_name == 'data_profiling' %}{{ source('claims_input','pharmacy_claim') }}{% else %}{{ref('pharmacy_claim')}}{% endif %}"



model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
