name: 'data_profiling'
version: '0.1.2'
config-version: 2


profile: 'default'

vars:

  eligibility: "{{ var('data_profiling_eligibility', var('claims_input_eligibility',ref('eligibility')))}}"
  medical_claim: "{{ var('data_profiling_medical_claim', var('claims_input_medical_claim',ref('medical_claim')))}}"
  pharmacy_claim: "{{ var('data_profiling_pharmacy_claim', var('claims_input_pharmacy_claim',ref('pharmacy_claim')))}}"



model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
