name: 'data_profiling'
version: '0.1.2'
config-version: 2


profile: 'default'

vars:
  eligibility: |
    {% if var('data_profiling_eligibility_override',none) is not none %}{{var('data_profiling_eligibility_override')}}
    {%- elif var('claims_input_eligibility_override',none) is not none %}{{var('claims_input_eligibility_override')}}
    {%- else %}{{ref('eligibility')}}
    {% endif %}
  medical_claim: |
    {% if var('data_profiling_medical_claim_override',none) is not none %}{{var('data_profiling_medical_claim_override')}}
    {%- elif var('claims_input_medical_claim_override',none) is not none %}{{var('claims_input_medical_claim_override')}}
    {%- else %}{{ref('medical_claim')}}
    {% endif %}
  pharmacy_claim: |
    {% if var('data_profiling_pharmacy_claim_override',none) is not none %}{{var('data_profiling_pharmacy_claim_override')}}
    {%- elif var('claims_input_pharmacy_claim_override',none) is not none %}{{var('claims_input_pharmacy_claim_override')}}
    {%- else %}{{ref('pharmacy_claim')}}
    {% endif %}

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
