name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'



vars:

## optional output config option 1 (configs apply to all tuva packages)
#
#  tuva_database: tuva
#  tuva_schema_prefix: test
#
## optional output config option 2 (package specific config), overrides option 1
#  data_profiling_database: tuva
#  data_profiling_schema: test_data_profiling


  cliams_input_eligibility: "{{source('claims_input','eligibility')"
  cliams_input_medical_claim: "{{source('claims_input','medical_claim')"
  cliams_input_pharmacy_claim: "{{source('claims_input','pharmacy_claim')"


### optional overrides for input data, only for use as a project
#  data_profiling_input_database: syntegra_synthetic_sample
#  data_profiling_input_schema: tuva_claims_input
#


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral